//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string SeatNum { get; set; }
        public Nullable<int> typeOfTicket { get; set; }
        public string address { get; set; }
        public string FlightConfirmNumber { get; set; }
        public string TicketPrice { get; set; }
        public Nullable<int> FlightID { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
