//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string Airline { get; set; }
        public string Flight_Number { get; set; }
        public Nullable<decimal> Economy_Price { get; set; }
        public Nullable<decimal> FirstClass_Price { get; set; }
        public Nullable<int> Seat_Capacity { get; set; }
        public Nullable<int> Seat_Left { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public Nullable<System.DateTime> Departure_Time { get; set; }
        public Nullable<System.DateTime> Arrival_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
